#!/usr/bin/env bash

set -euox pipefail

project_dir="$(realpath "$(dirname -- "$0")/../..")"
profile="$1"
build_dir="$BUILD_DIR_PARENT"/conan/"$profile"

# Create the build directory.
# Make it unique to the profile, in case multiple profiles are built.
mkdir -p "$build_dir"

# Initialise Conan.
conan config install "$project_dir"/.devcontainer/conan-config

# Install dependencies.
conan install \
    --build="missing" \
    --generator=CMakeDeps \
    --generator=CMakeToolchain \
    --output-folder="$build_dir" \
    --profile:build=scripts/conan/config/clang-release \
    --profile:host=scripts/conan/config/"$profile" \
    "$project_dir"
