#!/usr/bin/env bash

# run after invoking workspace/build with the same parameters

set -euox pipefail

build_subdir="$1"
build_dir="$BUILD_DIR_PARENT"/"$build_subdir"

# Go to the build directory.
cd "$build_dir"

# Initialize build environment.
# shellcheck source=/dev/null
source "$build_dir"/conanbuild.sh

# Build project.
cmake --build "$build_dir" --target clean
