#!/usr/bin/env bash

set -euox pipefail

project_dir="$(realpath "$(dirname -- "$0")/..")"
profile="$1"
profile_path=scripts/profiles/"$profile"
build_dir="$BUILD_DIR_PARENT"/"$profile"

# Create the build directory.
# Make it unique to the profile, in case multiple profiles are built.
mkdir -p "$build_dir"

# Initialise Conan.
conan config install "$project_dir"/.devcontainer/conan-config
conan profile detect --force

# Install dependencies.
conan install \
    --build="missing" \
    --generator=CMakeDeps \
    --generator=CMakeToolchain \
    --output-folder="$build_dir" \
    --profile="$profile_path" \
    "$project_dir"
