---
# tests of the checks required by CI, i.e. test tests
name: ci-test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'src/**'
      - 'CMakeLists.txt'
      - 'LICENCE'
      - 'README.md'
  workflow_dispatch:

jobs:
  tests:
    name: CI test
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/johnmcfarlane/simple-cpp:5
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: clang-debug
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - profile: clang-release
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "FALSE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "FALSE"
            trigger_warning: "FALSE"

          - profile: clang-test
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - profile: clang-test-fuzzer
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - profile: clang-test-tsan
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "FALSE"
            trigger_tsan: "TRUE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - profile: clang-tidy
            trigger_clang_tidy: "TRUE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - profile: gcc-debug
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - profile: gcc-release
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "FALSE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "FALSE"
            trigger_warning: "FALSE"

          - profile: gcc-test
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

    steps:
      - name: Cache build artefacts
        uses: actions/cache@v4
        with:
          key: ${{ matrix.profile }}-${{ hashFiles('conanfile.*') }}
          path: |
            ~/.conan2/p

      - name: Check out code
        uses: actions/checkout@v7

      - name: Build and run control tests
        env:
          TRIGGER_CLANG_TIDY: ${{ matrix.trigger_clang_tidy }}
          TRIGGER_STDLIB: ${{ matrix.trigger_stdlib }}
          TRIGGER_TSAN: ${{ matrix.trigger_tsan }}
          TRIGGER_UBSAN: ${{ matrix.trigger_ubsan }}
          TRIGGER_WARNING: ${{ matrix.trigger_warning }}
        run: |
          scripts/install ${{ matrix.profile }}
          scripts/build ${{ matrix.profile }} .github/workflows/ci-test
          scripts/test ${{ matrix.profile }}
