---
name: 'C++ test'

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/johnmcfarlane/simple-cpp
          imageName: ghcr.io/johnmcfarlane/simple-cpp
          imageTag: 5
          push: always

  unit-tests:
    name: test
    needs: build-image
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/johnmcfarlane/simple-cpp:5
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        profile:
          - clang-debug
          - clang-release
          - clang-test
          - clang-test-fuzzer
          - clang-test-tsan
          - clang-tidy
          - gcc-debug
          - gcc-gcov
          - gcc-release
          - gcc-test

    steps:
      - name: Cache build artefacts
        uses: actions/cache@v4
        with:
          key: ${{ matrix.profile }}-${{ hashFiles('conanfile.*') }}
          path: |
            ~/.conan2/p

      - name: Check out code
        uses: actions/checkout@v7

      - name: Build and run tests
        run: |
          scripts/install ${{ matrix.profile }}
          scripts/build ${{ matrix.profile }}
          scripts/test ${{ matrix.profile }}

      - name: Generate coverage report
        if: ${{ matrix.profile == 'gcc-gcov' }}
        run: |
          scripts/report ${{ matrix.profile }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        if: ${{ matrix.profile == 'gcc-gcov' }}
        with:
          name: coverage-report
          path: /root/builds/${{ matrix.profile }}/test-coverage.html
          if-no-files-found: error

  lint:
    name: lint
    needs: build-image
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/johnmcfarlane/simple-cpp:5
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Run linter
        run: scripts/lint
