---
name: 'C++ test'

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/johnmcfarlane/sample-cpp
          imageTag: 7
          push: always

  unit-tests:
    name: test
    needs: build-image
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/johnmcfarlane/sample-cpp:7
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: clang-asan
            pm: conan
          - profile: clang-debug
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: clang-asan
            pm: conan
          - profile: gcc-release
            pm: conan
          - profile: gcc-release
            pm: vcpkg

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Cache build artefacts
        uses: actions/cache@v6
        with:
          key: ${{ matrix.profile }}-${{ hashFiles(
            '.devcontainer/**',
            '.github/workflows/cpp-test.yml',
            'conanfile.*',
            'scripts/conan/install',
            'scripts/conan/profiles/${{ matrix.profile }}',
            'scripts/vcpkg/install',
            'scripts/vcpkg/triplets/${{ matrix.profile }}',
            'vcpkg-configuration.json',
            'vcpkg.json') }}
          path: |
            ~/.conan2/p
            ~/.cache/vcpkg/archives

      - name: Build
        run: scripts/${{ matrix.pm }}/install ${{ matrix.profile }}

      - name: Test
        run: scripts/${{ matrix.pm }}/build ${{ matrix.profile }}

      - name: Generate coverage report
        if: ${{ matrix.profile == 'gcc-gcov' }}
        run: scripts/report ${{ matrix.profile }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        if: ${{ matrix.profile == 'gcc-gcov' }}
        with:
          name: coverage-report
          path: /root/builds/${{ matrix.pm }}/${{ matrix.profile }}/test-coverage.html
          if-no-files-found: error

  lint:
    name: lint
    needs: build-image
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/johnmcfarlane/sample-cpp:7
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Run linter
        run: scripts/lint
