compiler:
    clang:
        version: ["23"]
        sanitizer: [null, AddressUndefinedBehavior, Fuzzer, ThreadUndefinedBehavior]
    gcc:
        version: ["16"]
        sanitizer: [null, AddressUndefinedBehavior]
